@baseURL = http://localhost:3000

### Rotas de API
GET {{baseURL}}/home/hello

###
GET {{baseURL}}/home/status

# @name ControllerAutomatico
###
GET {{baseURL}}/conceitos-automatico/home

###
GET {{baseURL}}/conceitos-automatico/outro

###
GET {{baseURL}}/conceitos-automatico/conceito

###
GET {{baseURL}}/recados

###
GET {{baseURL}}/recados/5

###
POST {{baseURL}}/recados
Content-Type: application/json

{
    "texto": "olo pessoal 4",
    "de": "ffsf",
    "para": "sadas"
}
###

PATCH {{baseURL}}/recados/5
Content-Type: application/json

{
  "texto": "opa opa eh",
  "lido": true
}

###

DELETE {{baseURL}}/recados/2


#Pessoas
### Listar todas as pessoas
GET {{baseURL}}/pessoas?page=1

### Listar uma pessoa pelo ID
GET {{baseURL}}/pessoas/1

### Criar uma nova pessoa
POST {{baseURL}}/pessoas
Content-Type: application/json 

{
  "name": "Usuario Teste {{$randomInt 100 999}}",
  "email": "usuario{{$timestamp}}@teste.com",
  "passwordHash": "Senh@123"
}

### Atualizar uma pessoa pelo ID
PATCH {{baseURL}}/pessoas/3
Content-Type: application/json
{
  "name": "Usuario Teste {{$randomInt 100 999}}",
  "email": "usuario{{$timestamp}}@teste.com",
  "passwordHash": "NovaSenha@123"
}

### Deletar uma pessoa pelo ID
DELETE {{baseURL}}/pessoas/4