@baseURL = http://localhost:3000

### Rotas de API
GET {{baseURL}}/home/hello

###
GET {{baseURL}}/home/status

# @name ControllerAutomatico
###
GET {{baseURL}}/conceitos-automatico/home

###
GET {{baseURL}}/conceitos-automatico/outro

###
GET {{baseURL}}/conceitos-automatico/conceito

###
GET {{baseURL}}/recados

###
GET {{baseURL}}/recados/2

###
POST {{baseURL}}/recados
Content-Type: application/json

{
    "texto": "olo pessoal 2",
    "de": "jonas",
    "para": "gui",
    "lido": false,
    "data": "2025-12-30T12:51:31.553Z"
  }
###

PATCH {{baseURL}}/recados/2
Content-Type: application/json

{
    "texto": "Este é o recado atualizado.",
    "de": "gui"
}

###

DELETE {{baseURL}}/recados/1